# Generated by Django 5.0.6 on 2024-06-18 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cattle_Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM'), ('Noon', 'Noon'), ('Other', 'Other')], max_length=20)),
                ('liters', models.FloatField()),
                ('density', models.FloatField()),
                ('prompt', models.TextField(blank=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cattle_Management.cattle')),
            ],
        ),
    ]
