# Generated by Django 5.0.6 on 2024-06-18 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cattle_Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('other_info', models.TextField()),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cattle_Management.cattle')),
            ],
        ),
    ]
