# Generated by Django 5.0.6 on 2024-06-18 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('photo', models.ImageField(upload_to='cattle_photos/')),
                ('father', models.CharField(max_length=100)),
                ('mother', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_type', models.CharField(choices=[('Dehorning', 'Dehorning'), ('Deworming', 'Deworming'), ('Vaccination', 'Vaccination'), ('Treatment', 'Treatment'), ('Spraying', 'Spraying'), ('Multi-Vitamin', 'Multi-Vitamin'), ('Iron Injection', 'Iron Injection')], max_length=20)),
                ('date', models.DateField()),
                ('method', models.CharField(blank=True, max_length=100)),
                ('drug', models.CharField(blank=True, max_length=100)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('veterinary_name', models.CharField(max_length=100)),
                ('chemical_used', models.CharField(blank=True, max_length=100)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cattle_Management.cattle')),
            ],
        ),
    ]
