# Generated by Django 5.0.6 on 2024-06-18 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cattle_Management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cattle',
            name='serial_number',
        ),
    ]
