# Generated by Django 5.0.6 on 2024-06-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cattle_Management', '0002_remove_cattle_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True),
        ),
    ]
